name: dg
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.6
  - numpy=1.24.4
  - pandas=2.1.1
  - scikit-learn=1.3.0
  - catboost=1.2.2
  - optuna=3.4.0
  - matplotlib=3.8.2
  - ipywidgets=8.1.1
  - notebook=7.0.6